config/routes.rb
MyFamily::Application.routes.draw do
  
  root :to => 'pages#home', :as => :home

  match "/signup" => 'users#new', :as => :signup
  match "/login" => 'user_sessions#new', :as => :login
  match "/logout" => 'user_sessions#destroy', :as => :logout
  
  resources :user_sessions
  
  resources :users do
    resources :people do
      member do
        get :add
      end
      resources :relationships
    end
  end
  

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :date_of_birth, :is_user, :name, :gender, :parent_id, :relationship_type
  attr_accessor :parent_id, :relationship_type
  
  belongs_to :user
  has_many :relationships, :dependent => :destroy
  has_many :reverse_relationships, :dependent => :destroy, :class_name => 'Relationship', :foreign_key => 'related_person_id', :dependent => :destroy
  
  before_create :define_gender
  after_create :create_relationship
  
  def define_gender
    r_type = RelationshipType.find_by_id(self.relationship_type)
    self.gender = r_type ? r_type.gender : 'male' #make it default to male just so we can make the graphics... eventually this would need to change
  end
  
  #I'm seperating this from doing it automatically incase I want to use it down the road
  def create_relationship
    relationship = Relationship.where(:person_id => self.parent_id, :related_person_id => self.id).first
    return if relationship
    Relationship.create(:person_id => self.parent_id, :related_person_id => self.id, :relationship_type_id => self.relationship_type)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :relationship_type_id, :person_id, :related_person_id
  
  belongs_to :relationship_type
  belongs_to :person
  belongs_to :related_person, :class_name => 'Person'
  
  validates :relationship_type_id, :person_id, :related_person_id, :presence => true
  
end
 

app/models/relationship_type.rb
class RelationshipType < ActiveRecord::Base
  attr_accessible :gender, :name
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :date_of_birth, :email, :name, :password, :password_confirmation, :gender
  
  acts_as_authentic do |c|
    c.login_field = :email
  end
  
  has_many :people
  
  after_create :create_initial_person
  
  def create_initial_person
    self.people.create(:date_of_birth => self.date_of_birth, :name => self.name, :gender => self.gender.downcase, :is_user => true)
  end
  
  def me
    self.people.find_by_is_user(true)
  end
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  #just to help rspec use it
  extend ActiveModel::Naming
  
  #just adding a couple things here to make authlogic sessions work
  
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  
  private
  
  def find_user
    @user = User.find(params[:user_id] || params[:id])
  end
  
  #some cool stuff that authlogic can do
  
  def require_user
    unless current_user
      respond_to do |format|
        format.html { redirect_to login_path, :notice => "You must be logged in to access this page" }
      end
      return false
    end
  end

  def require_no_user
    if current_user
      store_location
      redirect_to newsfeed_user_path(current_user.login)
      return false
    end
  end
  
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end
  
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'pages'
  
  def home
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  before_filter :find_user
  before_filter :require_user
  
  def index
    @person = @user.me
  end
  
  def add
    @person = Person.find_by_id(params[:person_id] || params[:id]) #so it returns nil if it can't be found
    @related_person = @user.people.build(params[:person])
  end
  
  def create 
    @related_person = @user.people.build(params[:person])
    @parent_id = params[:person][:parent_id]
    respond_to do |format|
      if @related_person.save
        format.html { redirect_to( user_person_path(@user, @parent_id)) } #, :notice => "You've created a new person!"
      else
        format.html { render :new, :notice => 'Something went wrong.'}
      end
    end
  end
  
  def show
    @person = Person.find(params[:person_id] || params[:id])
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  before_filter :find_user
  before_filter :find_person
  before_filter :require_user
  
  def index
  end
  
  def destroy
    @relationship = Relationship.find(params[:relationship_id] || params[:id])
    respond_to do |format|
      if @relationship.destroy
        format.html { redirect_to :back} #, :notice => "The person has been successfully removed!"
      else
        format.html { redirect_to :back} #, :notice => 'Something went wrong.'
      end
    end
  end
  
  private
  
  def find_person
    @person = Person.find(params[:person_id] || params[:id])
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  
  def new
    @user_session = UserSession.new
    respond_to do |format|
      format.html{render :layout => 'pages'}
    end
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    respond_to do |format|
      if @user_session.save
        format.html { redirect_to( user_people_path(@user_session.user))} #, :notice => 'Login Successfull')  I think they will know that...
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    respond_to do |format|
      format.html { redirect_to( login_path, :notice => 'You have been logged out') }
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :require_user, :only => [:show]
  
  def new
    @user = User.new
    respond_to do |format|
      format.html{render :layout => 'pages'}
    end
  end
  
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to( user_people_path(@user), :notice => 'Registration successfull.') }
      else
        format.html { render :new, :notice => 'Registration failed'}
      end
    end
  end
  
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html { redirect_to user_people_path(@user)}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title MyFamily
    = stylesheet_link_tag    "application", :media => "all" 
    = javascript_include_tag "application"
    = csrf_meta_tags 
  
  %body
    .container
      - if current_user
        #header_bar
          %a.logo_small{:href => user_people_path(current_user)}
          = link_to "Invite Your Family (Coming Soon)", '#'
          = link_to "Logout", logout_path
          .clr_flt
      - flash.each do |name, message|
        %div{:class => "flash flash_"+name.to_s}
          = message
      = yield

app/views/layouts/pages.html.haml
%html
  %head
    %title MyFamily
    = stylesheet_link_tag    "application", :media => "all" 
    = javascript_include_tag "application"
    = csrf_meta_tags 
  
  %body
    #header_logo
      %a.logo{:href => home_path}
    - if current_user
      = link_to "Logout", logout_path
    .container
      - flash.each do |name, message|
        %div{:class => "flash flash_"+name.to_s}
          = message
      = yield

app/views/pages/home.html.haml
%h1 A family tree is meant to be shared.
%h2 Create your family tree and invite your family members to help make it complete!  
#home_graphic
%a.signup_button{:href => signup_path}
%a.silent{:href => login_path}
  Already a member?
  Login here

app/views/people/add.html.haml
%h1 New Person
= form_for @related_person, :url => user_people_path(@user) do |f|
  - @related_person.errors.full_messages.each do |msg|
    = msg
  -if @person
    = f.hidden_field :parent_id, :value => @person.id
  %p
    = f.text_field :name, :placeholder => 'Name'
  %p
    = f.label :relationship_type
    %br/
    = f.select :relationship_type, options_for_select(RelationshipType.all.collect {|a| [a.name.capitalize.gsub('_', '-'), a.id]})
  %p
    = f.label :date_of_birth
    %br/
    = f.date_select :date_of_birth, :start_year => 1200, :end_year => Time.now.year
  %p
    = f.submit

app/views/people/index.html.haml
#user_section
  #center_user
    = render '/people/partials/person_large', :person => @user.me
  #surrounding_users
    - @user.me.relationships.each do |relationship|
      = render '/people/partials/person_small', :person => relationship.related_person, :relationship => relationship
    - @user.me.reverse_relationships.each do |relationship|
      = render '/people/partials/person_small', :person => relationship.person, :relationship => relationship
      
  

app/views/people/partials/_person_large.html.haml
.person.large{:id => 'person_'+person.id.to_s}
  .picture
    .add_person
      = link_to "+", add_user_person_path(@user, person), :title => "Add Person"
    %a.no_underline{:href => user_person_path(@user, person)}
      %span.image-wrap.large{:style => "background:url(/assets/user_icon_large_"+person.gender.downcase+".png) no-repeat center center;"}
  .name
    = person.name
  .born
    %strong
      Born:
    = person.date_of_birth.to_date

app/views/people/partials/_person_small.html.haml
.person.small{:id => 'person_'+person.id.to_s}
  .picture
    .add_person
      = link_to "+", add_user_person_path(@user, person), :title => "Add Person"
    - unless person.is_user
      .remove_person
        = link_to "-", user_person_relationship_path(@user, person, relationship), :title => "Remove Person", :method => 'delete', :confirm => "Are you sure you want to remove this person?"
    %a.no_underline{:href => user_person_path(@user, person)}
      %span.image-wrap.small{:style => "background:url(/assets/user_icon_small_"+person.gender.downcase+".png) no-repeat center center;"}
  .name
    = person.name
  .relationship_type{:class => person.gender}
    = relationship.relationship_type.name.capitalize.gsub('_', '-')
  .born
    %strong
      Born:
    = person.date_of_birth.to_date

app/views/people/show.html.haml
#user_section
  #center_user
    = render '/people/partials/person_large', :person => @person
  #surrounding_users
    - @person.relationships.each do |relationship|
      = render '/people/partials/person_small', :person => relationship.related_person, :relationship => relationship
    - @person.reverse_relationships.each do |relationship|
      = render '/people/partials/person_small', :person => relationship.person, :relationship => relationship

app/views/relationships/index.html.haml
%h1= @person.name

app/views/user_sessions/new.html.haml
%h1 Login
%h2 View, add, edit, and invite your family members.
= form_for @user_session do |f|
  -if @user_session.errors
    %ul#errors
      - @user_session.errors.full_messages.each do |msg|
        %li= msg
  %p
    = f.text_field :email, :placeholder => 'Email'
  %p
    = f.password_field :password, :placeholder => 'Password'
  %p
    = f.button "", :type => 'submit', :class => 'login_button', :id => 'login_button'
  %a.silent{:href => signup_path}
    New to Famingle?
    Sign up today!

app/views/users/new.html.haml
%h1 Sign up now!
%h2 Start creating your family tree today
= form_for @user do |f|
  -if @user.errors
    %ul#errors
      - @user.errors.full_messages.each do |msg|
        %li= msg
  %p
    = f.text_field :name, :placeholder => 'Name'
  %p
    = f.text_field :email, :placeholder => 'Email'
  %p
    = f.label :gender
    %br/
    = f.select :gender, options_for_select([ "Male", "Female" ], "Male")
  %p
    = f.label :date_of_birth
    %br/
    = f.date_select :date_of_birth, :start_year => 1200, :end_year => Time.now.year
  %p
    = f.password_field :password, :placeholder => 'Password'
  %p
    = f.password_field :password_confirmation, :placeholder => 'Password Confirmation'
  %p
    = f.button "", :type => 'submit', :class => 'signup_button', :id => 'signup_button'
  %a.silent{:href => login_path}
    Already a member?
    Login here
  
  